// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwhqyoubxkxcwpxfsmcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3aHF5b3VieGt4Y3dweGZzbWNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNjA3NjksImV4cCI6MjA2MTkzNjc2OX0.6rGrJSfhTCQ7w-ZiH4ig13r3ACJiiyhdlCksNaVB_Wo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);